const mongoose = require('mongoose');

// Define QRCode Schema
const qrCodeSchema = new mongoose.Schema({
  // Autogenerated ID will be added by default
  qrCodeImage: Buffer,
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
});

const QRCodeSchema = mongoose.model('QRCode', qrCodeSchema);

module.exports = { QRCodeSchema };